name: tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install deps
        run: yarn
      - name: run test
        run: yarn test